"""
Find the Difference
https://leetcode.com/explore/challenge/card/september-leetcoding-challenge/557/week-4-september-22nd-september-28th/3471/
Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.

Example:

Input:
s = "abcd"
t = "abcde"

Output:
e

Explanation:
'e' is the letter that was added.
"""


class Solution:
    def findTheDifference(self, s: str, t: str) -> str:
        # Solution 1 - 28 ms
        """
        s, t = sorted(s), sorted(t)
        for i in range(len(s)):
            if s[i] != t[i]:
                return t[i]

        return t[-1]
        """
        # Solution 2 - 12 ms
        for i in range(97, 97 + 26):
            if s.count(chr(i)) != t.count(chr(i)):
                return chr(i)

        # Solution 3 - 16 ms
        """
        for l in t:
            if t.count(l) > s.count(l): return l
        """


# Main Call
solution = Solution()
s = "abcd"
t = "abcde"

print(solution.findTheDifference(s, t))
